import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
    title: "DevOps Dynamics",
    description: "Generated by create next app",
    authors: [{ name: "Suyash Bhaswar", url: "" }],
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            <main className="py- mx-auto min-h-screen w-full max-w-7xl px-6 py-16">
                {children}
            </main>
            <Footer />
        </>
    );
}
